/* Licensed under the MIT License
   https://github.com/craigahobbs/bare-script-c/blob/main/LICENSE */

/* This file is generated by "make includes" - do not edit */

/*
 * The bundled BareScript include library
 *
 * Each include is embedded as its parser-compiled JSON script model, gzip-compressed.
 * An accessor decodes its include's model on first use and caches it; the
 * decoded text is released by bsIncludeCleanup. An include compiled out of the library
 * with its NO_BARESCRIPT_INCLUDE_<NAME> macro - see src/includeSource.c - keeps its
 * registry entry and accessor, which return no model.
 */

#ifndef BARESCRIPT_INCLUDE_SOURCE_H
#define BARESCRIPT_INCLUDE_SOURCE_H

#include <stddef.h>

#include "export.h"

#ifdef __cplusplus
extern "C" {
#endif

BS_VISIBILITY_BEGIN


/* The number of bundled include library scripts */
#define BS_INCLUDE_COUNT 32


/* A bundled include library script */
typedef struct BSIncludeSource {
    const char *name;
    const unsigned char *gzip;
    size_t gzipSize;
    char *decoded;
} BSIncludeSource;

/* The bundled include library registry, in name order */
extern BSIncludeSource bsIncludeSources[BS_INCLUDE_COUNT];

/* A bundled include library stub accessor - returns its include's decoded JSON script model */
typedef const char *(*BSIncludeSourceFn)(void);

/* The bundled include library stub accessors, in registry order */
extern const BSIncludeSourceFn bsIncludeSourceStubs[BS_INCLUDE_COUNT];


/*
 * The bundled include library stub accessors
 */

/* args.bare - the decoded JSON script model */
const char *bsIncludeSourceArgs(void);

/* baredoc.bare - the decoded JSON script model */
const char *bsIncludeSourceBaredoc(void);

/* baredocCLI.bare - the decoded JSON script model */
const char *bsIncludeSourceBaredocCLI(void);

/* barescriptLint.bare - the decoded JSON script model */
const char *bsIncludeSourceBarescriptLint(void);

/* barescriptModel.bare - the decoded JSON script model */
const char *bsIncludeSourceBarescriptModel(void);

/* barescriptParser.bare - the decoded JSON script model */
const char *bsIncludeSourceBarescriptParser(void);

/* base64.bare - the decoded JSON script model */
const char *bsIncludeSourceBase64(void);

/* data.bare - the decoded JSON script model */
const char *bsIncludeSourceData(void);

/* dataLineChart.bare - the decoded JSON script model */
const char *bsIncludeSourceDataLineChart(void);

/* dataTable.bare - the decoded JSON script model */
const char *bsIncludeSourceDataTable(void);

/* dataUtil.bare - the decoded JSON script model */
const char *bsIncludeSourceDataUtil(void);

/* diff.bare - the decoded JSON script model */
const char *bsIncludeSourceDiff(void);

/* draw.bare - the decoded JSON script model */
const char *bsIncludeSourceDraw(void);

/* elementModel.bare - the decoded JSON script model */
const char *bsIncludeSourceElementModel(void);

/* forms.bare - the decoded JSON script model */
const char *bsIncludeSourceForms(void);

/* gzip.bare - the decoded JSON script model */
const char *bsIncludeSourceGzip(void);

/* markdown.bare - the decoded JSON script model */
const char *bsIncludeSourceMarkdown(void);

/* markdownElements.bare - the decoded JSON script model */
const char *bsIncludeSourceMarkdownElements(void);

/* markdownHighlight.bare - the decoded JSON script model */
const char *bsIncludeSourceMarkdownHighlight(void);

/* markdownParser.bare - the decoded JSON script model */
const char *bsIncludeSourceMarkdownParser(void);

/* markdownString.bare - the decoded JSON script model */
const char *bsIncludeSourceMarkdownString(void);

/* markdownUp.bare - the decoded JSON script model */
const char *bsIncludeSourceMarkdownUp(void);

/* pager.bare - the decoded JSON script model */
const char *bsIncludeSourcePager(void);

/* qrcode.bare - the decoded JSON script model */
const char *bsIncludeSourceQrcode(void);

/* schema.bare - the decoded JSON script model */
const char *bsIncludeSourceSchema(void);

/* schemaDoc.bare - the decoded JSON script model */
const char *bsIncludeSourceSchemaDoc(void);

/* schemaParser.bare - the decoded JSON script model */
const char *bsIncludeSourceSchemaParser(void);

/* schemaTypeModel.bare - the decoded JSON script model */
const char *bsIncludeSourceSchemaTypeModel(void);

/* schemaUtil.bare - the decoded JSON script model */
const char *bsIncludeSourceSchemaUtil(void);

/* unittest.bare - the decoded JSON script model */
const char *bsIncludeSourceUnittest(void);

/* unittestMock.bare - the decoded JSON script model */
const char *bsIncludeSourceUnittestMock(void);

/* url.bare - the decoded JSON script model */
const char *bsIncludeSourceUrl(void);


BS_VISIBILITY_END

#ifdef __cplusplus
}
#endif

#endif
