/* Licensed under the MIT License
   https://github.com/craigahobbs/bare-script-c/blob/main/LICENSE */

/* This file is generated by "make includes" - do not edit */

/*
 * The bundled BareScript include library
 *
 * Each include is embedded as its parser-compiled script model in the binary encoding
 * bin/includeSource.bare describes, gzip-compressed. An accessor inflates its include's
 * model on first use and caches it for the calling thread; the bytes are released by
 * bsIncludeCleanup. An include compiled out of the library
 * with its NO_BARESCRIPT_INCLUDE_<NAME> macro - see src/includeSource.c - keeps its
 * registry entry and accessor, which return no model.
 */

#ifndef BARESCRIPT_INCLUDE_SOURCE_H
#define BARESCRIPT_INCLUDE_SOURCE_H

#include <stddef.h>

#include "export.h"

#ifdef __cplusplus
extern "C" {
#endif

BS_VISIBILITY_BEGIN


/* The number of bundled include library scripts */
#define BS_INCLUDE_COUNT 32


/* A bundled include library script */
typedef struct BSIncludeSource {
    const char *name;
    const unsigned char *gzip;
    size_t gzipSize;
} BSIncludeSource;

/* The bundled include library registry, in name order */
extern BSIncludeSource bsIncludeSources[BS_INCLUDE_COUNT];

/* The shared string table - the strings the optional includes' models refer to in common */
extern const BSIncludeSource bsIncludeSourceShared;

/* A bundled include library stub accessor - returns its include's inflated binary script model and its size */
typedef const unsigned char *(*BSIncludeSourceFn)(size_t *size);

/* The bundled include library stub accessors, in registry order */
extern const BSIncludeSourceFn bsIncludeSourceStubs[BS_INCLUDE_COUNT];


/*
 * The bundled include library stub accessors
 */

/* args.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceArgs(size_t *size);

/* baredoc.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceBaredoc(size_t *size);

/* baredocCLI.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceBaredocCLI(size_t *size);

/* barescriptLint.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceBarescriptLint(size_t *size);

/* barescriptModel.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceBarescriptModel(size_t *size);

/* barescriptParser.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceBarescriptParser(size_t *size);

/* base64.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceBase64(size_t *size);

/* data.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceData(size_t *size);

/* dataLineChart.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceDataLineChart(size_t *size);

/* dataTable.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceDataTable(size_t *size);

/* dataUtil.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceDataUtil(size_t *size);

/* diff.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceDiff(size_t *size);

/* draw.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceDraw(size_t *size);

/* elementModel.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceElementModel(size_t *size);

/* forms.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceForms(size_t *size);

/* gzip.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceGzip(size_t *size);

/* markdown.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceMarkdown(size_t *size);

/* markdownElements.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceMarkdownElements(size_t *size);

/* markdownHighlight.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceMarkdownHighlight(size_t *size);

/* markdownParser.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceMarkdownParser(size_t *size);

/* markdownString.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceMarkdownString(size_t *size);

/* markdownUp.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceMarkdownUp(size_t *size);

/* pager.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourcePager(size_t *size);

/* qrcode.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceQrcode(size_t *size);

/* schema.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceSchema(size_t *size);

/* schemaDoc.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceSchemaDoc(size_t *size);

/* schemaParser.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceSchemaParser(size_t *size);

/* schemaTypeModel.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceSchemaTypeModel(size_t *size);

/* schemaUtil.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceSchemaUtil(size_t *size);

/* unittest.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceUnittest(size_t *size);

/* unittestMock.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceUnittestMock(size_t *size);

/* url.bare - the inflated binary script model and its size */
const unsigned char *bsIncludeSourceUrl(size_t *size);


BS_VISIBILITY_END

#ifdef __cplusplus
}
#endif

#endif
